info:
  description: "Service for Product CRUD operations"

spring:
  application:
    name: product-service
#data:
  #mongodb:
  #uri: mongodb://localhost:27017/OMS

security:
  basic:
    enabled: false
logging:
  level: error
      #com.oms.product: debug
server:
  port: 9092
